language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.1.5"
  - "2.2.0"
  - "2.3.0"
before_script: 
  - echo "Remember your flashlight! Watch out for the lurking Grue!"
script: 
  - echo "BEGIN script BLOCK"
  - bundle exec ruby test/test_reve.rb
  #- bundle exec ruby test/test_extensions.rb


 




